// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'bankid_models.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'bankid_models.g.dart';

@freezed
class AuthResponse with _$AuthResponse {
  const factory AuthResponse({
    required String orderRef,
    required String autoStartToken
  }) = _AuthResponse;

  factory AuthResponse.fromJson(Map<String, Object?> json) =>
      _$AuthResponseFromJson(json);
}

@freezed
class CollectResponse with _$CollectResponse {
  const factory CollectResponse({
    required String orderRef,
    required String status,
    required String hintCode,
  }) = _CollectResponse;

  factory CollectResponse.fromJson(Map<String, Object?> json) =>
      _$CollectResponseFromJson(json);
}


@freezed
class OrderRefRequest with _$OrderRefRequest {
  const factory OrderRefRequest({
    required String orderRef,
  }) = _OrderRefRequest;

  factory OrderRefRequest.fromJson(Map<String, Object?> json) =>
      _$OrderRefRequestFromJson(json);
}

/*
@JsonSerializable()
class CollectResponse {
  const CollectResponse({this.orderRef, this.status, this.hintCode});

  factory CollectResponse.fromJson(Map<String, dynamic> json) => _$CollectResponseFromJson(json);

  final String? orderRef;
  final String? status;
  final String? hintCode;
  //final String? createdAt;

  Map<String, dynamic> toJson() => _$CollectResponseToJson(this);
}

 */
