name: Flutter CI

on:
  pull_request:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v5

    - uses: kuhnroyal/flutter-fvm-config-action/setup@v3

    - run: flutter pub get
    
    - run: dart format --set-exit-if-changed .
    
    - run: flutter analyze .
    
    - run: flutter test
    
#    - run: flutter build web --no-pub --no-tree-shake-icons
