name: Flutter CI

on:
  pull_request:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v5

    - name: Parse FVM configuration
      id: fvm-config-action
      run: |
        echo "FLUTTER_VERSION=$(jq -r '.flutter // empty' .fvmrc)" >> $GITHUB_OUTPUT
        echo "FLUTTER_CHANNEL=$(jq -r '.channel // empty' .fvmrc)" >> $GITHUB_OUTPUT

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

    - run: flutter pub get
    
    - run: dart format --set-exit-if-changed .
    
    - run: flutter analyze .
    
    - run: flutter test
    
#    - run: flutter build web --no-pub --no-tree-shake-icons
